### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by abb1991** [mtubes/prj-rev-bwfs-dasmoto#5]
I thought you had a very successful project overall! Your styling and code organization were both very strong. I added a few comments in your code about places where you might consider making a few minor changes, and some indications of best practices. I’d suggest pushing yourself to go through and  add consistent indentation and whitespacing to your HTML, and style all of your HTML elements with specific IDs and Classes (and when you’d want to use an id rather than a class), rather than accessing them through parent/child relationships. As an additional suggestion to push yourself further, look up Google Fonts and try adding ‘Lobster’ to your main header! Great work and keep it up!

**Comment by mtubes** [comment]
Thanks! I'll definitely apply those! Have a great day!
